[pytest]
asyncio_mode = auto
env =
    DATABASE_URL=postgresql+asyncpg://rahulrio@localhost:5432/codemind_test_db
    SECRET_KEY=TEST_SECRET_KEY
    GEMINI_API_KEY=test_key

testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
