import pytest
from httpx import AsyncClient
from app.config.settings import settings

API_STR = settings.API_V1_STR

@pytest.mark.asyncio
async def test_register_user_success(client: AsyncClient):
    """Test successful user registration."""
    payload = {
        "email": "newuser@codemind.ai",
        "password": "StrongPassword123!",
        "full_name": "New User"
    }
    response = await client.post(f"{API_STR}/auth/register", json=payload)
    
    assert response.status_code == 201
    data = response.json()
    assert data["email"] == payload["email"]
    assert data["full_name"] == payload["full_name"]
    assert "id" in data
    assert "password" not in data

@pytest.mark.asyncio
async def test_register_duplicate_user(client: AsyncClient, test_user: dict):
    """Test registering a user that already exists fails."""
    # Attempt to register the exact same user generated by the fixture
    response = await client.post(f"{API_STR}/auth/register", json=test_user)
    
    # Should conflict (usually 400 or 409)
    assert response.status_code in (400, 409)

@pytest.mark.asyncio
async def test_login_json_success(client: AsyncClient, test_user: dict):
    """Test successful JSON login endpoint."""
    payload = {
        "email": test_user["email"],
        "password": test_user["password"]
    }
    response = await client.post(f"{API_STR}/auth/login", json=payload)
    
    assert response.status_code == 200
    data = response.json()
    assert "access_token" in data
    assert data["token_type"] == "bearer"

@pytest.mark.asyncio
async def test_login_invalid_credentials(client: AsyncClient, test_user: dict):
    """Test login failure with incorrect password."""
    payload = {
        "email": test_user["email"],
        "password": "WrongPassword!999"
    }
    response = await client.post(f"{API_STR}/auth/login", json=payload)
    
    assert response.status_code in (401, 400)

@pytest.mark.asyncio
async def test_oauth2_token_success(client: AsyncClient, test_user: dict):
    """Test successful OAuth2 Form Data token endpoint."""
    data = {
        "username": test_user["email"],
        "password": test_user["password"]
    }
    # Form data uses 'data' instead of 'json'
    response = await client.post(f"{API_STR}/auth/token", data=data)
    
    assert response.status_code == 200
    resp_data = response.json()
    assert "access_token" in resp_data
    assert resp_data["token_type"] == "bearer"
