"""create document_contents table and update enum

Revision ID: 004_document_contents
Revises: 003_documents_table
Create Date: 2026-08-04 01:13:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '004_document_contents'
down_revision: Union[str, None] = '003_documents_table'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Update the ENUM by adding 'PROCESSED' and 'INDEXING'
    # Note: PostgreSQL does not easily support removing enum values inside a transaction, but adding is possible
    # We will just execute the raw SQL to add the value
    op.execute("ALTER TYPE documentstatus ADD VALUE IF NOT EXISTS 'PROCESSED'")
    op.execute("ALTER TYPE documentstatus ADD VALUE IF NOT EXISTS 'INDEXING'")
    
    # 2. Add sha256_hash to documents table
    op.add_column('documents', sa.Column('sha256_hash', sa.String(length=64), nullable=True))
    # Populate existing rows (if any) with a dummy hash, then make it NOT NULL
    op.execute("UPDATE documents SET sha256_hash = 'legacy' WHERE sha256_hash IS NULL")
    op.alter_column('documents', 'sha256_hash', existing_type=sa.String(length=64), nullable=False)
    
    # 3. Create the document_contents table
    op.create_table('document_contents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('character_count', sa.Integer(), nullable=False),
    sa.Column('processing_time_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document_contents')
    op.drop_column('documents', 'sha256_hash')
    # Note: We cannot easily remove 'PROCESSED' or 'INDEXING' from the ENUM in Postgres without dropping the type and recreating it,
    # which is omitted for this downgrade script simplicity.
    # ### end Alembic commands ###
