"""github_repository

Revision ID: ea225942638c
Revises: 005_document_chunks
Create Date: 2026-08-14 13:59:35.137622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea225942638c'
down_revision: Union[str, None] = '005_document_chunks'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repositories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('repository_url', sa.String(length=512), nullable=False),
    sa.Column('branch', sa.String(length=255), nullable=False),
    sa.Column('commit_sha', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repositories_project_id'), 'repositories', ['project_id'], unique=False)
    op.add_column('documents', sa.Column('source_type', sa.String(length=50), nullable=False, server_default='upload'))
    op.add_column('documents', sa.Column('repository_id', sa.Uuid(), nullable=True))
    op.add_column('documents', sa.Column('repo_file_path', sa.String(length=1024), nullable=True))
    op.create_foreign_key('documents_repository_id_fkey', 'documents', 'repositories', ['repository_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('documents_repository_id_fkey', 'documents', type_='foreignkey')
    op.drop_column('documents', 'repo_file_path')
    op.drop_column('documents', 'repository_id')
    op.drop_column('documents', 'source_type')
    op.drop_index(op.f('ix_repositories_project_id'), table_name='repositories')
    op.drop_table('repositories')
    # ### end Alembic commands ###
